### ISSUE TITLE
ボタン押下時に下の要素まで動いてしまう

### ISSUE THREAD

**Issue by negiissei** [TrpFrog/trpfrog-net#14]
## 内容の説明
現在linkButtonクラスの要素をクリックすると影が潰れるようになっている。
中身を覗いてみるとCSSで押下時にborder-bottom: none; が設定される方法が使われている。
しかし、そのやり方では縦幅が変わってしまい、下の要素の位置に影響が出てしまっている。

## URL
https://trpfrog.net/

## 環境
Windows 10
Firefox 94.0.2 (64bit)

## 詳しい説明
border-bottomの使用をやめ、

- position
- box-shadow
- top

を使う方法に変えると改善ができると思います。
参考までに。

**Comment by TrpFrog** [comment]
報告ありがとうございます。修正しました。
